name: CI

on: [ push ]

env:
  DSR_GPG_PASSWORD: ${{ secrets.DSR_GPG_PASSWORD }}
  DSR_REPO_USERNAME: ${{ secrets.DSR_REPO_USERNAME }}
  WEBSITE_DEPLOY_PATH: '/opt/dsr/web'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          ssh -t ${{env.DSR_REPO_USERNAME}}@desertskyrangers.com "mkdir -p ${{env.WEBSITE_DEPLOY_PATH}};" 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
          scp -B build/* ${{env.DSR_REPO_USERNAME}}@desertskyrangers.com:${{env.WEBSITE_DEPLOY_PATH}} 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
